[versions]
tg-bot = "9.1.0"
ksp = "2.3.4"
jackson = "2.21.0"
redis = "4.1.0"

kotlin = "2.3.0"

[libraries]
redisson = { module = "org.redisson:redisson", version.ref = "redis" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

[plugins]
telegram-bot = { id = "eu.vendeli.telegram-bot", version.ref = "tg-bot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }